org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRIds=true
android.nonFinalResIds=false
kotlin.code.style=official
# Kotlin 2.2.0 + AGP 8.8.2 + SDK 36
android.suppressUnsupportedCompileSdk=36
# buildConfig теперь включается в app/build.gradle.kts через buildFeatures.buildConfig = true
